import { useLayoutEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { projects } from "../../data/projects";
import "./SelectedWork.css";
import BlinkingSquares from "../BlinkingSquares/BlinkingSquares";
gsap.registerPlugin(ScrollTrigger);
function ExternalIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4h6v6M20 4 11 13M19 14v5H5V5h5"/></svg>}
function GitHubIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 .6a11.7 11.7 0 0 0-3.7 22.8c.6.1.8-.3.8-.6v-2.2c-3.3.7-4-1.4-4-1.4-.5-1.4-1.3-1.7-1.3-1.7-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1.1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.6-.3-5.3-1.3-5.3-5.8 0-1.3.5-2.4 1.2-3.3.1-.3-.5-1.6.1-3.3 0 0 1-.3 3.4 1.2a11.5 11.5 0 0 1 6.2 0c2.4-1.6 3.4-1.2 3.4-1.2.6 1.7.2 3 .1 3.3.8.9 1.2 2 1.2 3.3 0 4.5-2.7 5.5-5.3 5.8.4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.6A11.7 11.7 0 0 0 12 .6Z"/></svg>}
function ProjectCard({project,index}){const card=useRef(null);const image=useRef(null);const info=useRef(null);function enter(){gsap.to(card.current,{y:-6,duration:.7,ease:"power4.out"});gsap.to(image.current,{scale:1.055,duration:1.1,ease:"power3.out"});gsap.to(info.current,{y:-3,duration:.7,ease:"power4.out"})}function leave(){gsap.to(card.current,{y:0,duration:.7,ease:"power4.out"});gsap.to(image.current,{scale:1,duration:1.1,ease:"power3.out"});gsap.to(info.current,{y:0,duration:.7,ease:"power4.out"})}return <article ref={card} className="work-card" data-work-card onMouseEnter={enter} onMouseLeave={leave}><a className="work-card__visual" href={project.liveUrl} target="_blank" rel="noreferrer" aria-label={"View "+project.name}><img ref={image} src={project.previewImage} alt={project.name+" website homepage"}/><div className="work-card__shade"/><div className="work-card__top"><span>0{index+1}</span><span>{project.type}</span></div><div className="work-card__bottom"><h3>{project.name}</h3><span className="work-card__arrow"><ExternalIcon/></span></div></a><div ref={info} className="work-card__info"><p>{project.description}</p><div className="work-card__links">{project.repoUrl&&<a className="work-card__icon" href={project.repoUrl} target="_blank" rel="noreferrer" aria-label={project.name+" GitHub repository"}><GitHubIcon/></a>}<a className="work-card__view" href={project.liveUrl} target="_blank" rel="noreferrer">VIEW LIVE SITE <span>↗</span></a></div></div></article>}
function SelectedWork(){const section=useRef(null);const track=useRef(null);useLayoutEffect(()=>{const ctx=gsap.context(()=>{const cards=gsap.utils.toArray("[data-work-card]");const viewport=section.current.querySelector(".selected-work__viewport");gsap.set(cards,{opacity:0,y:70,clipPath:"inset(8% 0 4% 0)"});cards.forEach(card=>{gsap.set(card.querySelector("img"),{scale:1.12});gsap.set(card.querySelector(".work-card__info"),{y:24,opacity:0})});gsap.set(cards[0],{opacity:1,y:0,clipPath:"inset(0% 0 0% 0)"});gsap.set(cards[0].querySelector("img"),{scale:1});gsap.set(cards[0].querySelector(".work-card__info"),{y:0,opacity:1});const getDistance=()=>Math.max(0,track.current.scrollWidth-viewport.querySelector(".work-scroll").clientWidth);const timeline=gsap.timeline({scrollTrigger:{trigger:section.current,start:"top top",end:()=>"+="+getDistance(),pin:viewport,pinSpacing:true,scrub:1,anticipatePin:1,invalidateOnRefresh:true}});timeline.to(cards.slice(1),{opacity:1,y:0,clipPath:"inset(0% 0 0% 0)",duration:.22,stagger:.06,ease:"power3.out"},.12).to(cards.slice(1).map(card=>card.querySelector("img")),{scale:1,duration:.28,stagger:.06,ease:"power2.out"},.12).to(cards.slice(1).map(card=>card.querySelector(".work-card__info")),{y:0,opacity:1,duration:.2,stagger:.06,ease:"power2.out"},.2).to(track.current,{x:()=>-getDistance(),duration:1,ease:"none"},.55);ScrollTrigger.refresh();return()=>timeline.scrollTrigger?.kill()},section);return()=>ctx.revert()},[]);return <section id="work" className="selected-work" ref={section}><div className="selected-work__squares"><BlinkingSquares direction="right" gridSize={58} squareSize={.48} fadeStart={.58} fadeEnd={1} falloff={1.6} minBrightness={.28} twinkleSpeed={.7} twinkleStrength={.55} intensity={.65} opacity={.42} squareColor="#3451B2" backgroundColor="transparent" dpr={1.5}/></div><div className="selected-work__viewport"><div className="section-inner"><div className="work-head"><div><span className="section-kicker">SELECTED WORKS</span><h2>SELECTED<br/><em>WORKS.</em></h2></div><a className="github-link" href="https://github.com/Immanuelchika099" target="_blank" rel="noreferrer" aria-label="IMAN GitHub"><GitHubIcon/></a></div><div className="work-scroll"><div className="work-track" ref={track}>{projects.map((project,index)=><ProjectCard key={project.id} project={project} index={index}/>)}</div></div></div></div><a className="all-projects-button" href="https://github.com/Immanuelchika099" target="_blank" rel="noreferrer">VIEW ALL PROJECTS <span>↗</span></a></section>}
export default SelectedWork;